# Generated by Django 3.2.16 on 2022-12-06 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactme',
            name='Email',
            field=models.EmailField(max_length=50),
        ),
    ]
