# Generated by Django 3.2.16 on 2022-12-16 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_contactme_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactme',
            old_name='Concern',
            new_name='Message',
        ),
        migrations.RenameField(
            model_name='contactme',
            old_name='Phone',
            new_name='Subject',
        ),
    ]
