# Generated by Django 3.2.16 on 2022-12-16 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20221216_2227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactme',
            old_name='Message',
            new_name='Concern',
        ),
        migrations.RenameField(
            model_name='contactme',
            old_name='Subject',
            new_name='Phone',
        ),
    ]
